# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: generic_session_app_notification.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'generic_session_app_notification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&generic_session_app_notification.proto\x12\x11\x64unedaq.notifidaq\x1a\x1bgoogle/protobuf/empty.proto\"A\n\x16\x41pplicationInitialised\x12\'\n\x07payload\x18\x01 \x01(\x0b\x32\x16.google.protobuf.Empty\"=\n\x12\x41pplicationStarted\x12\'\n\x07payload\x18\x01 \x01(\x0b\x32\x16.google.protobuf.Empty\"S\n(ApplicationAdvertisedConnectivityService\x12\'\n\x07payload\x18\x01 \x01(\x0b\x32\x16.google.protobuf.Empty\"Y\n.ApplicationUnregisteredFromConnectivityService\x12\'\n\x07payload\x18\x01 \x01(\x0b\x32\x16.google.protobuf.Empty\"3\n\x08Shutdown\x12\'\n\x07payload\x18\x01 \x01(\x0b\x32\x16.google.protobuf.Empty\"B\n\x17\x43ontrollerFoundChildren\x12\'\n\x07payload\x18\x01 \x01(\x0b\x32\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generic_session_app_notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPLICATIONINITIALISED']._serialized_start=90
  _globals['_APPLICATIONINITIALISED']._serialized_end=155
  _globals['_APPLICATIONSTARTED']._serialized_start=157
  _globals['_APPLICATIONSTARTED']._serialized_end=218
  _globals['_APPLICATIONADVERTISEDCONNECTIVITYSERVICE']._serialized_start=220
  _globals['_APPLICATIONADVERTISEDCONNECTIVITYSERVICE']._serialized_end=303
  _globals['_APPLICATIONUNREGISTEREDFROMCONNECTIVITYSERVICE']._serialized_start=305
  _globals['_APPLICATIONUNREGISTEREDFROMCONNECTIVITYSERVICE']._serialized_end=394
  _globals['_SHUTDOWN']._serialized_start=396
  _globals['_SHUTDOWN']._serialized_end=447
  _globals['_CONTROLLERFOUNDCHILDREN']._serialized_start=449
  _globals['_CONTROLLERFOUNDCHILDREN']._serialized_end=515
# @@protoc_insertion_point(module_scope)
