# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notification.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'notification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12notification.proto\x12\x11\x64unedaq.notifidaq\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"z\n\x06Origin\x12-\n\x06system\x18\x01 \x01(\x0e\x32\x1d.dunedaq.notifidaq.SystemType\x12\x15\n\rinstance_name\x18\x02 \x01(\t\x12\x19\n\x0csession_name\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x0f\n\r_session_name\"\x8f\x01\n\x0cNotification\x12)\n\x06source\x18\x01 \x01(\x0b\x32\x19.dunedaq.notifidaq.Origin\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12%\n\x07payload\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any*\x96\x01\n\nSystemType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0e\n\nCONTROLLER\x10\x01\x12\x13\n\x0f\x44\x41Q_APPLICATION\x10\x02\x12\x13\n\x0fPROCESS_MANAGER\x10\x03\x12\x13\n\x0fSESSION_MANAGER\x10\x04\x12\x14\n\x10RESOURCE_MANAGER\x10\x05\x12\x16\n\x12\x41UTHORISER_SERVICE\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYSTEMTYPE']._serialized_start=372
  _globals['_SYSTEMTYPE']._serialized_end=522
  _globals['_ORIGIN']._serialized_start=101
  _globals['_ORIGIN']._serialized_end=223
  _globals['_NOTIFICATION']._serialized_start=226
  _globals['_NOTIFICATION']._serialized_end=369
# @@protoc_insertion_point(module_scope)
