"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _SystemType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _SystemTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_SystemType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    UNKNOWN: _SystemType.ValueType  # 0
    CONTROLLER: _SystemType.ValueType  # 1
    DAQ_APPLICATION: _SystemType.ValueType  # 2
    PROCESS_MANAGER: _SystemType.ValueType  # 3
    SESSION_MANAGER: _SystemType.ValueType  # 4
    RESOURCE_MANAGER: _SystemType.ValueType  # 5
    AUTHORISER_SERVICE: _SystemType.ValueType  # 6

class SystemType(_SystemType, metaclass=_SystemTypeEnumTypeWrapper): ...

UNKNOWN: SystemType.ValueType  # 0
CONTROLLER: SystemType.ValueType  # 1
DAQ_APPLICATION: SystemType.ValueType  # 2
PROCESS_MANAGER: SystemType.ValueType  # 3
SESSION_MANAGER: SystemType.ValueType  # 4
RESOURCE_MANAGER: SystemType.ValueType  # 5
AUTHORISER_SERVICE: SystemType.ValueType  # 6
global___SystemType = SystemType

class _AppNotificationType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _AppNotificationTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_AppNotificationType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    Modules_Initialised: _AppNotificationType.ValueType  # 0

class AppNotificationType(_AppNotificationType, metaclass=_AppNotificationTypeEnumTypeWrapper): ...

Modules_Initialised: AppNotificationType.ValueType  # 0
global___AppNotificationType = AppNotificationType

class _ControllerNotificationType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ControllerNotificationTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ControllerNotificationType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    Controller_FoundChildren: _ControllerNotificationType.ValueType  # 0

class ControllerNotificationType(_ControllerNotificationType, metaclass=_ControllerNotificationTypeEnumTypeWrapper): ...

Controller_FoundChildren: ControllerNotificationType.ValueType  # 0
global___ControllerNotificationType = ControllerNotificationType

@typing.final
class Origin(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SYSTEM_FIELD_NUMBER: builtins.int
    INSTANCE_NAME_FIELD_NUMBER: builtins.int
    SESSION_NAME_FIELD_NUMBER: builtins.int
    system: global___SystemType.ValueType
    instance_name: builtins.str
    session_name: builtins.str
    def __init__(
        self,
        *,
        system: global___SystemType.ValueType = ...,
        instance_name: builtins.str = ...,
        session_name: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_session_name", b"_session_name", "session_name", b"session_name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_session_name", b"_session_name", "instance_name", b"instance_name", "session_name", b"session_name", "system", b"system"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_session_name", b"_session_name"]) -> typing.Literal["session_name"] | None: ...

global___Origin = Origin

@typing.final
class Notification(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SOURCE_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    APP_TYPE_FIELD_NUMBER: builtins.int
    CONTROLLER_TYPE_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    app_type: global___AppNotificationType.ValueType
    controller_type: global___ControllerNotificationType.ValueType
    @property
    def source(self) -> global___Origin: ...
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def payload(self) -> google.protobuf.any_pb2.Any: ...
    def __init__(
        self,
        *,
        source: global___Origin | None = ...,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        app_type: global___AppNotificationType.ValueType = ...,
        controller_type: global___ControllerNotificationType.ValueType = ...,
        payload: google.protobuf.any_pb2.Any | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["app_type", b"app_type", "controller_type", b"controller_type", "payload", b"payload", "source", b"source", "timestamp", b"timestamp", "typed_notification_type", b"typed_notification_type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["app_type", b"app_type", "controller_type", b"controller_type", "payload", b"payload", "source", b"source", "timestamp", b"timestamp", "typed_notification_type", b"typed_notification_type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["typed_notification_type", b"typed_notification_type"]) -> typing.Literal["app_type", "controller_type"] | None: ...

global___Notification = Notification
